{"name": "Авторизация с недействительными учетными данными", "status": "passed", "steps": [{"name": "Открыть страницу авторизации", "status": "passed", "start": 1728403465924, "stop": 1728403466793}, {"name": "Ввести в форму авторизации недействительные учетные данные", "status": "passed", "start": 1728403466794, "stop": 1728403466881}, {"name": "Отображается ошибка - Invalid credentials. Please try again.", "status": "passed", "start": 1728403466881, "stop": 1728403466885}], "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1728403465924, "stop": 1728403466886, "uuid": "bb3330e5-a082-48fa-ac5d-b239ecbfdbdb", "historyId": "3230c37a4ddf37e226b736e144aaba65", "testCaseId": "89a909a1ca222b871b75e39c89c26fa1", "fullName": "tests.test_login#test_login_failure", "labels": [{"name": "feature", "value": "Авторизация"}, {"name": "severity", "value": "critical"}, {"name": "story", "value": "Авторизация недействительные учетные данные"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "48652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}